TOKEN   = "975449712b54d5463a9bc22eddfacb006D57EA7D1C7F73A4690338D42F14313ED12D0C1F"
SMTP_SERVER = "smtp-mail.outlook.com"
SMTP_PORT   = 587
SMTP_USER   = "no-reply@dbs.rs"
SMTP_PASS   = "Z#308765449963uw"
RECIPIENTS  = "miljan.stankovic@dbs.rs"
